### ISSUE TITLE
Arrows missing in DM_pH plots

### ISSUE THREAD

**Issue by JohannaPedersen** [AU-BCE-EE/Pedersen-2023-app-digestate-NH3-review#8]
/lit_raw_vs_dig/scripts/plot.R
I wanted to change the size of a plot, new plot: /plots/DM_pH_effectsB. 
Problems with geom_smooth() after a reinstallation of R so now arrow heads are missing.

**Comment by sashahafner** [comment]
From @JohannaPedersen:

I get errors with running: render('stats1.Rmd', output_dir = '../stats') and then the next lines are not run, and therefore the points were missing for the plot. 

Long-term solution is to avoid including Rmd -> pdf. 
See https://github.com/sashahafner/R-template/issues/3
